# Generated by Django 5.1.1 on 2024-09-18 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Number', models.CharField(max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('Profile_pic', models.ImageField(null=True, upload_to='Media/Profile_Pic')),
                ('Carer_Summary', models.TextField(max_length=100, null=True)),
                ('age', models.PositiveIntegerField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
