# Generated by Django 5.0.7 on 2024-09-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_languagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
